version: "3.3"

services:
  influxdb:
    container_name: influxdb
    image: quay.io/influxdb/influxdb:2.0.6
    volumes:
      - ./influxdb:/root/.influxdbv2/
    ports:
      - 8086:8086
    networks:
      - "viernes"

networks:
  viernes:
    external: true

